SunriseCo/Controllers/BranchesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SunriseCo.Data;
using SunriseCo.Models;

namespace SunriseCo.Controllers
{
    public class BranchesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BranchesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Branches
        public async Task<IActionResult> Index()
        {
              return View(await _context.Branchs.ToListAsync());
        }

        // GET: Branches/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Branchs == null)
            {
                return NotFound();
            }

            var branch = await _context.Branchs
                .FirstOrDefaultAsync(m => m.Id == id);
            if (branch == null)
            {
                return NotFound();
            }

            return View(branch);
        }

        // GET: Branches/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Branches/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Address")] Branch branch)
        {
            if (ModelState.IsValid)
            {
                _context.Add(branch);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(branch);
        }

        // GET: Branches/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Branchs == null)
            {
                return NotFound();
            }

            var branch = await _context.Branchs.FindAsync(id);
            if (branch == null)
            {
                return NotFound();
            }
            return View(branch);
        }

        // POST: Branches/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Address")] Branch branch)
        {
            if (id != branch.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(branch);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BranchExists(branch.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(branch);
        }

        // GET: Branches/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Branchs == null)
            {
                return NotFound();
            }

            var branch = await _context.Branchs
                .FirstOrDefaultAsync(m => m.Id == id);
            if (branch == null)
            {
                return NotFound();
            }

            return View(branch);
        }

        // POST: Branches/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Branchs == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Branchs'  is null.");
            }
            var branch = await _context.Branchs.FindAsync(id);
            if (branch != null)
            {
                _context.Branchs.Remove(branch);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BranchExists(int id)
        {
          return _context.Branchs.Any(e => e.Id == id);
        }
    }
}

SunriseCo/Controllers/EmployeesController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SunriseCo.Data;
using SunriseCo.Models;

namespace SunriseCo.Controllers
{
    public class EmployeesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public EmployeesController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        public string GreetVisitor()
        {
            return "Welcome to sunrise for software solution";
        }

        public string GreetUser(string name)
        {
            return "Hi "+ name + "!";
        }

        public double GetPrice (double cost, double profitRatio)
        {
            return cost + cost * profitRatio;
        }

        [Route("[controller]/List")]
        [HttpGet] // Not Necessary - Get by Default
        public IActionResult GetIndexView(string? search, string? sortType, string? sortOrder, int pageSize = 2, int pageNumber = 1)
        {
            //List<Employee> emps = new List<Employee> ();
            IQueryable<Employee> emps = _context.Employees.AsQueryable();

            if(!string.IsNullOrWhiteSpace(search))
            {
                //emps = _context.Employees.ToList ();
                search = search.Trim();
                emps = _context.Employees.Where(e => e.FullName.Contains(search));
            }
            //else
            //{
            //    search = search.Trim();
            //    emps = _context.Employees.Where(e => e.FullName.Contains(search)).ToList();
                
            //}

            if(!string.IsNullOrWhiteSpace(sortType) && !string.IsNullOrWhiteSpace(sortOrder))
            {
                if(sortType == "FullName")
                {
                    if (sortOrder == "asc")
                        emps = emps.OrderBy(e => e.FullName);
                    else if(sortOrder == "desc")
                        emps = emps.OrderByDescending(e => e.FullName);
                }

                else if (sortType == "Position")
                {
                    if (sortOrder == "asc")
                        emps = emps.OrderBy(e => e.Position);
                    else if (sortOrder == "desc")
                        emps = emps.OrderByDescending(e => e.Position);
                }

                else if (sortType == "Salary")
                {
                    if (sortOrder == "asc")
                        emps = emps.OrderBy(e => e.Salary);
                    else if (sortOrder == "desc")
                        emps = emps.OrderByDescending(e => e.Salary);
                }
            }

            ViewBag.CurrentSearch = search;

            emps = emps.Skip(pageSize * (pageNumber - 1)).Take(pageSize);
            ViewBag.pageSize = pageSize;
            ViewBag.pageNumber = pageNumber;

            return View("Index", emps.ToList());
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View(_context.Employees);
        }

        [HttpGet]
        public IActionResult GetDetailsView(int id)
        {
            Employee employee = _context.Employees.Include(e => e.Department).FirstOrDefault(Item => Item.Id == id);
            if(employee == null)
                return NotFound();
            return View("Details", employee);
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            Employee employee = _context.Employees.Include(e => e.Department).FirstOrDefault(Item => Item.Id == id);
            if (employee == null)
                return NotFound();
            return View(employee);
        }

        [HttpGet]
        public IActionResult GetCreateView()
        {
            ViewBag.AllDepartments = _context.Departments.ToList(); // For Selection Department When creating new Employee
            return View("Details");
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.AllDepartments = _context.Departments.ToList();
            return View();
        }

        [ValidateAntiForgeryToken] // To Prevent CSRF attacks
        [HttpPost] // It's necessary to define the method
        // [Bind()] => prevents over-posting attacks
        public IActionResult AddEmployee([Bind("Id,FullName,Position,Salary,Bonus,PhoneNumber,Email,ConfirmEmail,Password,ConfirmPassword," +
            "HiringDateTime,BirthDate,AttendanceTime,LeavingTime,CreatedAt,LastUpdateAt,DepartmentId")] Employee employee,
            IFormFile? imageFile)
        {
            if (ModelState.IsValid == true)
            {
                if(imageFile == null)
                {
                    employee.ImageUrl = "\\images\\No_Image.png";
                }
                else
                {
                    string imgUrl = "\\images\\" + Guid.NewGuid() + Path.GetExtension(imageFile.FileName);
                    employee.ImageUrl = imgUrl;

                    string imgPath = _webHostEnvironment.WebRootPath + imgUrl;

                    FileStream imgStream = new FileStream(imgPath, FileMode.Create);
                    imageFile.CopyTo(imgStream);
                    imgStream.Dispose();
                }

                employee.CreatedAt = DateTime.Now;

                _context.Employees.Add(employee);
                _context.SaveChanges();
                return RedirectToAction("GetIndexView");
            }
            else
            {
                ViewBag.AllDepartments = _context.Departments.ToList();
                return View("Create");
            }
           
        }

        [HttpGet]
        public IActionResult GetEditView(int id)
        {
            Employee employee = _context.Employees.FirstOrDefault(Item => Item.Id == id);
            if (employee == null)
            {
                return NotFound();
            }
            ViewBag.AllDepartments = _context.Departments.ToList();
            return View("Edit", employee);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            Employee employee = _context.Employees.FirstOrDefault(Item => Item.Id == id);
            if (employee == null)
            {
                return NotFound();
            }
            ViewBag.AllDepartments = _context.Departments.ToList();
            return View(employee);
        }

        [ValidateAntiForgeryToken] // To Prevent CSRF attacks
        [HttpPost] // It's necessary to define the method
                   // [Bind()] => prevents over-posting attacks
        public IActionResult EditEmployee(int id, [Bind("Id,FullName,Position,Salary,Bonus,PhoneNumber,Email,ConfirmEmail,Password," +
            "ConfirmPassword,HiringDateTime,BirthDate,AttendanceTime,LeavingTime,CreatedAt,LastUpdateAt,DepartmentId," +
            "ImageUrl")] Employee employee, IFormFile? imageFile)
        {
            if (id != employee.Id)
            {
                return BadRequest();
            }
            if (ModelState.IsValid == true)
            {
                if(imageFile != null)
                {
                    if(employee.ImageUrl != "\\images\\No_Image.png")
                    {
                        string oldImgPath = _webHostEnvironment.WebRootPath + employee.ImageUrl;
                        if(System.IO.File.Exists(oldImgPath))
                        {
                            System.IO.File.Delete(oldImgPath);
                        }
                    }
                    //string imgExtension = Path.GetExtension(imageFile.FileName);
                    //Guid imgGuid = Guid.NewGuid();
                    //string imgName = imgGuid + imgExtension;
                    string imgUrl = "\\images\\" + Guid.NewGuid() + Path.GetExtension(imageFile.FileName);
                    //string imgUrl = "\\images\\" + imgName;
                    employee.ImageUrl = imgUrl;

                    string imgPath = _webHostEnvironment.WebRootPath + imgUrl;
                    FileStream imgStream = new FileStream(imgPath, FileMode.Create);
                    imageFile.CopyTo(imgStream);
                    imgStream.Dispose();
                }

                employee.LastUpdateAt = DateTime.Now;

                _context.Employees.Update(employee);
                _context.SaveChanges();
                return RedirectToAction("GetIndexView");
            }
            else
            {
                ViewBag.AllDepartments = _context.Departments.ToList();
                return View("Edit", employee);
            }
        }

        [HttpGet]
        public IActionResult GetDeleteView(int id)
        {
            Employee employee = _context.Employees.FirstOrDefault(Item => Item.Id == id);
            if (employee == null)
            {
                return NotFound();
            }
            return View("Delete", employee);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            Employee employee = _context.Employees.FirstOrDefault(Item => Item.Id == id);
            if (employee == null)
            {
                return NotFound();
            }
            return View(employee);
        }

        [HttpPost] // It's necessary to define the method
        public IActionResult DeleteEmployee(int id)
        {
            Employee employee = _context.Employees.FirstOrDefault(Item => Item.Id == id);

            if (employee.ImageUrl != "\\images\\No_Image.png")
            {
                string imgPath = _webHostEnvironment.WebRootPath + employee.ImageUrl;
                System.IO.File.Delete(imgPath);
            }

            _context.Employees.Remove(employee);
            _context.SaveChanges();
            return RedirectToAction("GetIndexView");
        }
    }
}

SunriseCo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SunriseCo</title>
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    @*<link href="~/css/solar.min.css" rel="stylesheet" />*@
    <link href="~/css/darkly.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SunriseCo.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link href="~/lib/font-awesome/css/all.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">SunriseCo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Employees" asp-action="GetIndexView">Employees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Departments" asp-action="GetIndexView">Departments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Branches" asp-action="Index">Brances</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - SunriseCo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SunriseCo/Views/Shared/_NewLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SunriseCo</title>
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    @*<link href="~/css/solar.min.css" rel="stylesheet" />*@
    <link href="~/css/darkly.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SunriseCo.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
</head>
<body>
    <h1 style="background-color: cyan; color:maroon" class="text-center">Before</h1>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <h1 style="background-color: maroon; color:cyan" class="text-center">After</h1>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - SunriseCo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SunriseCo/Views/Shared/hrSupport.cshtml
<div class="card row" style="width:250px;">
    Contact HR Support
    <i class="bi bi-envelope"> Hr_Support@sunrise.com</i>
    <i class="bi bi-phone">02004006007</i>
</div>