SunriseCo/Models/Department.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel.DataAnnotations;

namespace SunriseCo.Models
{
    public class Department
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "You have to provide a valid name")]
        [MinLength(2, ErrorMessage = "Name mustn't be less than 2 Characters")]
        [MaxLength(20, ErrorMessage = "Name mustn't be exceed 20 Characters")]
        public string Name { get; set; }

        [Required(ErrorMessage = "You have to provide a valid description")]
        [MinLength(5, ErrorMessage = "Description name mustn't be less than 5 Characters")]
        [MaxLength(50, ErrorMessage = "Description mustn't be exceed 50 Characters")]
        public string Description { get; set; }

        // Navigation Property
        [ValidateNever]
        public ICollection<Employee> Employees { get; set; }
    }
}

SunriseCo/Controllers/DepartmentsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore;
using SunriseCo.Data;
using SunriseCo.Models;

namespace SunriseCo.Controllers
{
    public class DepartmentsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DepartmentsController(ApplicationDbContext context)
        {
            _context = context;
        }

        [HttpGet] // Not Necessary - Get by Default
        public IActionResult GetIndexView()
        {
            return View("Index", _context.Departments);
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View(_context.Departments);
        }

        [HttpGet]
        public IActionResult GetDetailsView(int id)
        {
            Department department = _context.Departments.Include(d => d.Employees).FirstOrDefault(Item => Item.Id == id);
            if (department == null)
                return NotFound();
            return View("Details", department);
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            Department department = _context.Departments.Include(d => d.Employees).FirstOrDefault(Item => Item.Id == id);
            if (department == null)
                return NotFound();
            return View(department);
        }

        [HttpGet]
        public IActionResult GetCreateView()
        {
            return View("Details");
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [ValidateAntiForgeryToken] // To Prevent CSRF attacks
        [HttpPost] // It's necessary to define the method
        // [Bind()] => prevents over-posting attacks
        public IActionResult AddDepartment([Bind("Id,Name,Description")] Department department)
        {
            if (ModelState.IsValid == true)
            {
                _context.Departments.Add(department);
                _context.SaveChanges();
                return RedirectToAction("GetIndexView");
            }
            else
            {
                return View("Create");
            }

        }

        [HttpGet]
        public IActionResult GetEditView(int id)
        {
            Department department = _context.Departments.FirstOrDefault(Item => Item.Id == id);
            if (department == null)
            {
                return NotFound();
            }
            return View("Edit", department);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            Department department = _context.Departments.FirstOrDefault(Item => Item.Id == id);
            if (department == null)
            {
                return NotFound();
            }
            return View(department);
        }

        [ValidateAntiForgeryToken] // To Prevent CSRF attacks
        [HttpPost] // It's necessary to define the method
        // [Bind()] => prevents over-posting attacks
        public IActionResult EditDepartment(int id, [Bind("Id,Name,Description")] Department department)
        {
            if (id != department.Id)
            {
                return BadRequest();
            }
            if (ModelState.IsValid)
            {
                _context.Departments.Update(department);
                _context.SaveChanges();
                return RedirectToAction("GetIndexView");
            }
            else
            {
                return View("Edit");
            }
        }

        [HttpGet]
        public IActionResult GetDeleteView(int id)
        {
            Department department = _context.Departments.FirstOrDefault(Item => Item.Id == id);
            if (department == null)
            {
                return NotFound();
            }
            return View("Delete", department);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            Department department = _context.Departments.FirstOrDefault(Item => Item.Id == id);
            if (department == null)
            {
                return NotFound();
            }
            return View(department);
        }

        [HttpPost] // It's necessary to define the method
        public IActionResult DeleteDepartment(int id)
        {
            Department department = _context.Departments.FirstOrDefault(Item => Item.Id == id);
            _context.Departments.Remove(department);
            _context.SaveChanges();
            return RedirectToAction("GetIndexView");
        }
    }
}

SunriseCo/Views/Departments/Create.cshtml
@model Department

<h1 style="background-color: cyan; color:maroon" class="text-center">
    This Create Page for Departments
</h1>

<div class="row">
    <form method="post" asp-controller="Departments" asp-action="AddDepartment" class=" col-4">
        <div asp-validation-summary="All" class="text-danger"></div>
        <div>
            <label>Name</label>
            <input type="text" asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div>
            <label>Description</label>
            <input type="text" asp-for="Description" class="form-control" />
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <div><button type="submit" class="btn btn-primary mt-2">Add</button></div>
    </form>
</div>


<br/>
<a asp-controller="Departments" asp-action="GetIndexView" class="btn btn-success">Back To List</a>

SunriseCo/Views/Departments/Delete.cshtml
@* Delete Page *@


@model Department

<h1 class="alert alert-danger text-center" style="color:darkred">
    Are you sure that you want to delete this department ?
</h1>


<dl class="row">
    <dt class="col-1">Id</dt>
    <dd class="col-11">@Model.Id</dd>

    <dt class="col-1">Name</dt>
    <dd class="col-11">@Model.Name</dd>

    <dt class="col-1">Description</dt>
    <dd class="col-11">@Model.Description</dd>
</dl>

<form method="post" asp-controller="Departments" asp-action="DeleteDepartment">
    <input type="hidden" asp-for="Id"/>
    <button type="submit" class="btn btn-danger mb-2">Delete</button>
</form>

<a asp-controller="Departments" asp-action="GetIndexView" class="btn btn-success">Back To Departments</a>

SunriseCo/Views/Departments/Details.cshtml
@* Details Page *@


@model Department

<h1 style="background-color: cyan; color:maroon">
    Welcome to Details Page for Departments
</h1>


<dl>
    <dt>Id</dt>
    <dd>@Model.Id</dd>
    <dt>Name</dt>
    <dd>@Model.Name</dd>
    <dt>Description</dt>
    <dd>@Model.Description</dd>
</dl>

<h3>Employees:</h3>
<ul class="list-group mb-5">
    @foreach (var employee in Model.Employees)
    {
        <li class="list-group-item list-group-item-primary">@employee.FullName</li>
    }
</ul>

<a asp-controller="Departments" asp-action="GetIndexView" class="btn btn-success">Back To Departments</a>

SunriseCo/Views/Departments/Edit.cshtml
@model Department

<h1 style="background-color: cyan; color:maroon" class="text-center">
    This is Edit Page for Departments
</h1>

<div class="row">
    <form method="post" asp-controller="Departments" asp-action="EditDepartment" class="col-4">
        <div asp-validation-summary="All" class="text-danger"></div>

        <input type="hidden" asp-for="Id" />

        <div>
            <label>Name</label>
            <input type="text" asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div>
            <label>Description</label>
            <input type="text" asp-for="Description" class="form-control" />
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <div><button type="submit" class="btn btn-primary mt-2">Edit</button></div>
    </form>
</div>



<br />
<a asp-controller="Departments" asp-action="GetIndexView" class="btn btn-success">Back To List</a>

SunriseCo/Views/Departments/Index.cshtml
@* Departments Page *@

@model IEnumerable<Department>

<h1 style="background-color: cyan; color:maroon" class="text-center">   
    This Departments Index Page
</h1>

<a asp-controller="Departments" asp-action="Create" class="btn btn-success mb-2">Create New</a>

@if (Model.Count() > 0)
{
    <table class="table table-bordered table-striped table-hover">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Position</th>
                <th>More...</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Id</td>
                    <td>@item.Name</td>
                    <td>@item.Description</td>
                    <td>
                        <a asp-controller="Departments" asp-action="GetDetailsView" asp-route-id=@item.Id class="btn btn-success">
                            Details
                        </a>
                        <a asp-controller="Departments" asp-action="GetEditView" asp-route-id=@item.Id class="btn btn-primary">
                            Edit
                        </a>
                        <a asp-controller="Departments" asp-action="GetDeleteView" asp-route-id=@item.Id class="btn btn-danger">
                            Delete
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    //<div ></div>
    <h1  class="alert alert-danger text-white text-center">
        !! There is no data yet !!
    </h1>
}

<br />
<a asp-controller="Home" asp-action="Index" class="btn btn-success">Back Home</a>